#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install haproxy -y

# Define your new IP addresses
web_server_1_ip=34.232.65.159
web_server_2_ip=54.237.22.167

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 $web_server_1_ip:80 check
    server web-02 $web_server_2_ip:80 check
EOT

# Test HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy
sudo systemctl restart haproxy
